### PR TITLE
Home Assistant 0.99.3

### PR DESCRIPTION
**Pull request by andr2000**
This is rather a huge pull request which probably could be split, but still.
This PR adds support for the latest (ATM) version of HomeAssistant 0.99.3:
1. Remove unused recipes
2. Update those which are still needed
3. Add new required ones

This basically works, but please expect more changes when I touch components/integrations/sensors of HA.
Known issues:
1. chromecast is not integrated
2. You name it

Thank you

### CODE REVIEW

**Comment by andr2000** [comment]
I forgot to mention that HA now wants python >= 3.6, so there is a requirement for warrior now which provides python 3.7.2

**Comment by bachp** [comment]
@andr2000 Thanks for the PR.

For me it is fine to make warrior a requirement.

I don't have the means to test this, so I will just look trough your changes and then merge them.

**Comment by andr2000** [comment]
Thank you! 
Well, I will definitely add more recipes and fixes as I progress with HA. Unfortunately there is no easy way to check if all the requirements are met unless you step into some new previously untested component ;)

**Comment by moto-timo** [comment]
First of all, thank you for the upgrade. It's been on my todo list for a while.

It appears you have been quite aggressive with your deletions, for instance the yahoo weather component requires yahooweather:

https://github.com/home-assistant/home-assistant/blob/dev/requirements_all.txt#L2007

Can you revisit your deletions and make sure they aren't required by sub-components?

**Comment by moto-timo** [comment]
I've been intending to add support for the technologies I use: HomeKit, ecobee and Z-wave. Currently running on OpenHab2...

**Comment by andr2000** [comment]
@moto-timo As I said I am not able to test all the functionality, so I decided to leave only those components which are needed for HA to start. For example, I need ebusd component which I didn't put into the PR. So, I was just not sure when to stop, e.g. we cannot have all the components integrated (unless someone is brave enough to solve all the dependencies and those of the additional components itself ;). That was the reason for aggressive deletion.
We can probably get to some acceptable HA configuration in a step-by-step manner, e.g. have basic functionality running and then adding new components. But I am not quite sure we can have something which will fit all the use-cases. Or we have to install pip on the target...

**Comment by andr2000** [comment]
How about
 ```
├── meta-homeassistant
 │   ├── recipes-devtools
 │   │   └── python
 ----------------> **HA base components to make it running - this is what I have now**
 │   ├── recipes-homeassistant
 │   │   ├── homeassistant
 │   │   │   └── python3-home-assistant-frontend_20190919.1.bb
 │   │   └── images
 │   │       └── core-image-homeassistant.bb
 │   └── recipes-integrations
 │           └── python
 ----------------> **put all additional components and their dependencies here**
 │               └── python3-ebusdpy_0.0.16.bb
 
```

so we put all additional components in *recipes-integrations*, e.g. ebusd in my case and yahoo in yours?

**Comment by bachp** [comment]
@andr2000 The original idea to not have pip in the target was to be able to use a read only rootfs and the posibility to use it offline. My preferred way would be to have an automated test for every integration that is supported by this layer so we know they are working. Not sure how feasible this is tough.

Another approach would be to have some kind of heuristic that tries to find missing packages by parsing `requirements_all.txt`. In the ideal case this layer would provide everything that is needed for all integrations, but this might be to big.

And I like your proposal to have the essential dependencies from the integration ones.

**Comment by andr2000** [comment]
I also tend to have NO pip installed, but it can always be added depending on other people use-cases and in other people's bbappends ;)
So, I would go with "base" HA and then "recipes-integrations". Base can be way easier validated by itself and then every time we add a new integration it needs to be validated separately.

**Comment by bachp** [comment]
I'm currently traying to add a CI job that builds the home assistant image https://github.com/bachp/meta-homeassistant/tree/ci but it seems the current repo doesn't work with master and warrior.

**Comment by andr2000** [comment]
cool, I indeed had daemonize recipe, but in a different meta layer ;)

**Comment by moto-timo** [comment]
@bachp  the warrior build probably failed because the kas-warrior.yml file is missing the layers for meta-openembedded (sync it with kas-master.yml). It looks like the master build halted because warrior had already failed. The .gitlab-ci.yml is expecting kas.yml, but now we have kas-warrior.yml and kas-master.yml

**Comment by bachp** [comment]
@moto-timo `kas-warrior.yml` derives from `kas-master.yml` it just overrides the branch so this should work. I think the issue is that `python3-daemonize` is missing. @andr2000 Can you add it?

The `.gitlab-ci.yml` is currently not used as I was focusing on Github Actions for the moment. I should probably remove it in oder to avoid confusion.

**Comment by andr2000** [comment]
@bachp I did, see bf332359558612f70a17b9b9a01f37855373a16d

**Pull request merged**
