### PR TITLE
[RFC] Ha 0.99.3 integrations

### PR DESCRIPTION
**Pull request by andr2000**
This is an RFC PR to show the way I see adding new/restoring/updating old integrations.
The commits should have `[integrations]` tag, it would be good if base HA will have `[base]` or `[core]`
tags to distinguish.

### CODE REVIEW

**Comment by bachp** [comment]
I like the idea, i think it makes it easier.

One side note. I think we can stop doing the python3 packages with include files as python2 is soon eol anyway.

**Comment by andr2000** [comment]
Well, I do support python2 drop whenever possible, but if I borrow an existing recipe and update it to HA needs then I prefer to keep the original implementation. For instance, if recipe comes from OE and is implemented with .inc then we should better keep it as is for easier sync in the future. All new components should be created without .inc.

**Comment by bachp** [comment]
Agree. But this leads to the question how we want to deal with packages from other layers. Do we want to update them in meta-pythonnfor example, or should we keep copies of the required versions in this layer?

**Comment by andr2000** [comment]
I was first thinking that copying recipes from other meta layers is a bad idea (and it actually is).
But at the end of the end we might end up with a bunch of meta layers being included providing "existing recipes we do not want to have a copy of" (I expect conflicts so hello BBMASK hustle)
So, for example, we may have local copies of the updated recipes form meta-python and might want to upstream those. But, once those merged we might not be immediately able to use those as usually those go into master or release we are not yet ready or can use. E.g. we are at warrior, but new recipes in some other new release.
So, IMO:
1. Have copies and have those as close to their initial implementation as possible.
2. Try to upstream changes.

...And it is also possible that the maintainers of those repos we want to upstream to might not want to accept the changes for many reasons. Stability, testing etc.

**Comment by moto-timo** [comment]
As co-founder and co-maintainer of meta-python, I would strongly recommend upstreaming and not copying recipes from at least that layer. Pascal and I had a long discussion at ELCE about whether to put the meta-homeassistant recipes in meta-python, but decided  to keep the homeassistant-specific functionality in this layer.

**Comment by moto-timo** [comment]
Also, I have plans to create a meta-python2 layer for all the folks that insist they cannot change. meta-python itself will therefore become python3 only and we will merge the .inc files. They make devtool upgrade a mess to work with...and we only went down that path because of the need to support two python major versions. Until python4 comes out of course ;)

**Comment by andr2000** [comment]
> As co-founder and co-maintainer of meta-python, I would strongly recommend upstreaming and not copying recipes from at least that layer. 
Agree, that is always the right goal to have everything upstream, so you have less work maintaining your meta layer

The questions I cannot answer here are:
1. For example, we need a specific version of a recipe - should we create a local copy then?
2. If a recipe we need is not yet available in warrior, but is available in master - what do we do?
3. If a recipe belongs to some other maintained meta layer, should we add that to the project dependencies and make sure we only use those recipes we need (BBMASK)?

**Comment by bachp** [comment]
@moto-timo As I don't have a lot of time anymore to maintain this I'm not opposed to bring this to meta-python if this is still desired?

**Comment by andr2000** [comment]
@bachp May I ask you what was the reason for closing this PR?

**Comment by bachp** [comment]
@andr2000 It was automatically closed as it targeted a branch (bachp:ha_0.99.3) that no longer exists. 
I can't change the target branch so I can't reopen it. Can you?

**Comment by andr2000** [comment]
superseded by #36

**Pull request closed without merging**
